type TemplateEngine = (data: any) => string;
export default class jTDAL {
    private static readonly _keywords;
    private static readonly _regexpPatternPath;
    private static readonly _regexpPatternString;
    private static readonly _regexpPatternMacro;
    private static readonly _regexpPatternPathBoolean;
    private static readonly _regexpPatternExpressionAllowedBoolean;
    private static readonly _regexpPatternExpressionAllowedBooleanMacro;
    private static readonly _regexpTagWithTDAL;
    private static readonly _regexpTagAttributes;
    private static readonly _regexpPathString;
    private static readonly _regexpCondition;
    private static readonly _regexpRepeat;
    private static readonly _regexpContent;
    private static readonly _regexpAttributes;
    private static readonly _regexpAttributesTDAL;
    private static readonly _HTML5VoidElements;
    private _macros;
    private _trim;
    private _strip;
    private static _ParseString;
    private static _ParsePath;
    constructor(trim?: boolean, strip?: boolean);
    private _Parse;
    MacroAdd(macroName: string, template: string): boolean;
    private _Compile;
    CompileToFunction(template: string): TemplateEngine;
    CompileToString(template: string): string;
}
export {};
